version: '3.1'

services:

  db:
    environment:
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=posgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./psql_setup/load_db.sh:/docker-entrypoint-initdb.d/load_db.sh
      - ./psql_setup/:/tmp/psql_setup/

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
